version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: backend-dev
    container_name: lumin-backend
    volumes:
      - ./backend:/app  # Mount backend code for hot-reloading
    ports:
      - "8000:8000"  # Map FastAPI port
    environment:
      - PYTHONPATH=/app  # Set the PYTHONPATH
      - PYTHONDONTWRITEBYTECODE=1
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload  # Enable FastAPI hot-reloading

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: frontend-dev
    container_name: lumin-frontend
    volumes:
      - ./src:/app/src  # Mount frontend src for hot-reloading
      - ./public:/app/public  # Mount public directory
      - /app/node_modules  # To ensure node_modules are not overwritten
    ports:
      - "3000:3000"
    command: npm run dev
    depends_on:
      - backend  # Ensures the backend service is running